# Generated by Django 3.2.14 on 2022-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tenth_uid', models.IntegerField()),
                ('twelth_uid', models.IntegerField()),
                ('aadhar_no', models.IntegerField()),
                ('email_1', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('uni_roll', models.IntegerField()),
                ('board', models.CharField(max_length=50)),
            ],
        ),
    ]
