# Generated by Django 3.2.14 on 2022-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihrestapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
